import { 
  TrendingUp, 
  PiggyBank, 
  Landmark, 
  CalendarDays, 
  ReceiptText 
} from "lucide-react";

export const calculatorGroups = [
  {
    id: "investments",
    label: "Investments",
    icon: TrendingUp,
    calculators: [
      {
        id: "sip",
        title: "SIP Calculator",
        description:
          "Estimate how regular monthly investments could grow over time.",
        endpoint: "/calculators/sip",
        fields: [
          {
            name: "monthlyInvestment",
            label: "Monthly investment",
            placeholder: "5000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "annualReturn",
            label: "Expected annual return",
            placeholder: "12",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Investment period",
            placeholder: "10",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "totalInvestment",
            label: "Total investment",
            currency: true,
          },
          {
            key: "wealthGained",
            label: "Wealth gained",
            currency: true,
          },
          {
            key: "estimatedValue",
            label: "Estimated value",
            currency: true,
            primary: true,
          },
        ],
      },
      {
        id: "lumpsum",
        title: "Lumpsum Calculator",
        description:
          "Estimate the future value of a one-time investment.",
        endpoint: "/calculators/lumpsum",
        fields: [
          {
            name: "investment",
            label: "Investment amount",
            placeholder: "100000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "annualReturn",
            label: "Expected annual return",
            placeholder: "12",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Investment period",
            placeholder: "10",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "investment",
            label: "Initial investment",
            currency: true,
          },
          {
            key: "wealthGained",
            label: "Wealth gained",
            currency: true,
          },
          {
            key: "futureValue",
            label: "Future value",
            currency: true,
            primary: true,
          },
        ],
      },
      {
        id: "roi",
        title: "ROI Calculator",
        description:
          "Understand the profit or loss generated by an investment.",
        endpoint: "/calculators/return-on-investment",
        fields: [
          {
            name: "investment",
            label: "Initial investment",
            placeholder: "100000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "currentValue",
            label: "Current value",
            placeholder: "125000",
            prefix: "₹",
            type: "number",
          },
        ],
        results: [
          {
            key: "investment",
            label: "Investment",
            currency: true,
          },
          {
            key: "profit",
            label: "Profit / loss",
            currency: true,
          },
          {
            key: "roi",
            label: "Return on investment",
            suffix: "%",
            primary: true,
        },
        ],
      },
    ],
  },
  {
    id: "savings",
    label: "Savings",
    icon: PiggyBank,
    calculators: [
      {
        id: "simple-interest",
        title: "Simple Interest",
        description:
          "Calculate interest earned on a principal amount over time.",
        endpoint: "/calculators/simple-interest",
        fields: [
          {
            name: "principal",
            label: "Principal amount",
            placeholder: "100000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "7",
            suffix: "%",
            type: "number",
          },
          {
            name: "time",
            label: "Time",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "simpleInterest",
            label: "Interest earned",
            currency: true,
          },
          {
            key: "totalAmount",
            label: "Total amount",
            currency: true,
            primary: true,
          },
        ],
      },
      {
        id: "compound-interest",
        title: "Compound Interest",
        description:
          "See how your money grows when interest compounds over time.",
        endpoint: "/calculators/compound-interest",
        fields: [
          {
            name: "principal",
            label: "Principal amount",
            placeholder: "100000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "8",
            suffix: "%",
            type: "number",
          },
          {
            name: "time",
            label: "Time",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "interest",
            label: "Interest earned",
            currency: true,
          },
          {
            key: "maturityAmount",
            label: "Maturity amount",
            currency: true,
            primary: true,
          },
        ],
      },
      {
        id: "fd",
        title: "Fixed Deposit",
        description:
          "Estimate the maturity amount and interest earned on an FD.",
        endpoint: "/calculators/fd",
        fields: [
          {
            name: "principal",
            label: "Deposit amount",
            placeholder: "100000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "7",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Tenure",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
          {
            name: "frequency",
            label: "Compounding frequency",
            type: "select",
            options: [
              { value: 1, label: "Yearly" },
              { value: 2, label: "Half-yearly" },
              { value: 4, label: "Quarterly" },
              { value: 12, label: "Monthly" },
            ],
          },
        ],
        results: [
          {
            key: "principal",
            label: "Principal",
            currency: true,
          },
          {
            key: "interestEarned",
            label: "Interest earned",
            currency: true,
          },
          {
            key: "maturityAmount",
            label: "Maturity amount",
            currency: true,
            primary: true,
          },
        ],
      },
      {
        id: "rd",
        title: "Recurring Deposit",
        description:
          "Estimate how regular monthly deposits could grow over time.",
        endpoint: "/calculators/rd",
        fields: [
          {
            name: "monthlyDeposit",
            label: "Monthly deposit",
            placeholder: "5000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "7",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Tenure",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "totalDeposit",
            label: "Total deposits",
            currency: true,
          },
          {
            key: "interestEarned",
            label: "Interest earned",
            currency: true,
          },
          {
            key: "maturityAmount",
            label: "Maturity amount",
            currency: true,
            primary: true,
          },
        ],
      },
    ],
  },
  {
    id: "loans",
    label: "Loans",
    icon: Landmark,
    calculators: [
      {
        id: "personal-loan-emi",
        title: "Personal Loan EMI",
        description:
          "Calculate your monthly EMI and total loan interest.",
        endpoint: "/calculators/personal-loan-emi",
        fields: [
          {
            name: "principal",
            label: "Loan amount",
            placeholder: "500000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "10",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Loan tenure",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "monthlyEMI",
            label: "Monthly EMI",
            currency: true,
            primary: true,
          },
          {
            key: "totalInterest",
            label: "Total interest",
            currency: true,
          },
          {
            key: "totalPayment",
            label: "Total payment",
            currency: true,
          },
        ],
      },
      {
        id: "home-loan-emi",
        title: "Home Loan EMI",
        description:
          "Estimate monthly payments and total interest on a home loan.",
        endpoint: "/calculators/home-loan-emi",
        fields: [
          {
            name: "principal",
            label: "Loan amount",
            placeholder: "3000000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "8.5",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Loan tenure",
            placeholder: "20",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "monthlyEMI",
            label: "Monthly EMI",
            currency: true,
            primary: true,
          },
          {
            key: "totalInterest",
            label: "Total interest",
            currency: true,
          },
          {
            key: "totalPayment",
            label: "Total payment",
            currency: true,
          },
        ],
      },
      {
        id: "car-loan-emi",
        title: "Car Loan EMI",
        description:
          "Estimate the monthly cost of financing a vehicle.",
        endpoint: "/calculators/car-loan-emi",
        fields: [
          {
            name: "principal",
            label: "Loan amount",
            placeholder: "800000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "9",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Loan tenure",
            placeholder: "5",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "monthlyEMI",
            label: "Monthly EMI",
            currency: true,
            primary: true,
          },
          {
            key: "totalInterest",
            label: "Total interest",
            currency: true,
          },
          {
            key: "totalPayment",
            label: "Total payment",
            currency: true,
          },
        ],
      },
      {
        id: "education-loan-emi",
        title: "Education Loan EMI",
        description:
          "Understand repayment costs for an education loan.",
        endpoint: "/calculators/education-loan-emi",
        fields: [
          {
            name: "principal",
            label: "Loan amount",
            placeholder: "1000000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "rate",
            label: "Annual interest rate",
            placeholder: "8",
            suffix: "%",
            type: "number",
          },
          {
            name: "years",
            label: "Loan tenure",
            placeholder: "10",
            suffix: "years",
            type: "number",
          },
        ],
        results: [
          {
            key: "monthlyEMI",
            label: "Monthly EMI",
            currency: true,
            primary: true,
          },
          {
            key: "totalInterest",
            label: "Total interest",
            currency: true,
          },
          {
            key: "totalPayment",
            label: "Total payment",
            currency: true,
          },
        ],
      },
    ],
  },
  {
    id: "planning",
    label: "Planning",
    icon: CalendarDays,
    calculators: [
      {
        id: "retirement",
        title: "Retirement Calculator",
        description:
          "Estimate the corpus you could build before retirement.",
        endpoint: "/calculators/retirement",
        fields: [
          {
            name: "currentAge",
            label: "Current age",
            placeholder: "30",
            type: "number",
          },
          {
            name: "retirementAge",
            label: "Retirement age",
            placeholder: "60",
            type: "number",
          },
          {
            name: "monthlyInvestment",
            label: "Monthly investment",
            placeholder: "10000",
            prefix: "₹",
            type: "number",
          },
          {
            name: "annualReturn",
            label: "Expected annual return",
            placeholder: "10",
            suffix: "%",
            type: "number",
          },
        ],
        results: [
          {
            key: "totalInvestment",
            label: "Total investment",
            currency: true,
          },
          {
            key: "wealthCreated",
            label: "Wealth created",
            currency: true,
          },
          {
            key: "retirementCorpus",
            label: "Retirement corpus",
            currency: true,
            primary: true,
          },
        ],
      },
    ],
  },
  {
    id: "tax",
    label: "Tax",
    icon: ReceiptText,
    calculators: [
      {
        id: "income-tax",
        title: "Income Tax Calculator",
        description:
          "Get an estimate of your income tax based on your annual income.",
        endpoint: "/calculators/income-tax",
        fields: [
          {
            name: "annualIncome",
            label: "Annual income",
            placeholder: "1000000",
            prefix: "₹",
            type: "number",
          },
        ],
        results: [
          {
            key: "estimatedTax",
            label: "Estimated tax",
            currency: true,
            primary: true,
          },
          {
            key: "incomeAfterTax",
            label: "Income after tax",
            currency: true,
          },
        ],
      },
    ],
  },
];

export const calculators = calculatorGroups.flatMap(
  (group) => group.calculators
);